<table width="100%" border="1">
    <thead>
        <tr>
            <td>ID</th>
            <th>Book</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->book): ?>
        <tr>
            <td><?php echo $this->book["id"]; ?></td>
            <td><?php echo $this->book["name"]; ?></td>
            <td><?php echo $this->book["author"]; ?></td>
        </tr>
        <?php else: ?>
        <tr>
            <td colspan="3">Invalid book!</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
