<table width="100%" border="1">
    <thead>
        <tr>
            <td>ID</th>
            <th>Book</th>
            <th>Author</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->book): ?>
        <tr>
            <td><?php echo $this->book["id"]; ?></td>
            <td><?php echo $this->book["name"]; ?></td>
            <td><?php echo $this->book["author"]; ?></td>
            <td><a href="/book/delete/id/<?php echo $this->book["id"]; ?>">Delete</a></td>
        </tr>
        <?php else: ?>
        <tr>
            <td colspan="3">Invalid book!</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php if ($this->book["picture"]) : ?>
<img src="/images/<?php echo $this->book["picture"]; ?>" alt="book" style="width:600px; margin-top: 10px;"/>
<?php endif; ?>

<p style="text-align: right"><a href="/">Back to Home</a></p>
